# Generated by Django 2.1.1 on 2018-11-10 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('category', models.CharField(max_length=256)),
                ('price_req', models.IntegerField()),
                ('price', models.FloatField()),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_msg', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('good_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('reciever_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('good_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('detail', models.TextField()),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('category', models.CharField(max_length=256)),
                ('sale_or_require', models.IntegerField()),
                ('price', models.FloatField()),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_msg', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=256)),
                ('pic_count', models.IntegerField()),
                ('category', models.IntegerField()),
                ('good_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('feedback_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('skey', models.CharField(max_length=256)),
                ('contact_info', models.CharField(max_length=256)),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
