# Generated by Django 2.1.1 on 2018-11-24 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('collect_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('detail', models.TextField()),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('detail', models.TextField()),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=256)),
                ('task_id', models.IntegerField()),
                ('feedback_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_credit', models.IntegerField(default=100)),
                ('goods_or_activity', models.IntegerField()),
                ('label', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('category', models.CharField(max_length=256)),
                ('price_for_goods', models.FloatField()),
                ('price_for_activity', models.CharField(max_length=256)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_msg', models.TextField()),
                ('status', models.IntegerField()),
                ('undercarriage_reason', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('skey', models.CharField(max_length=256)),
                ('avatar_url', models.CharField(max_length=256)),
                ('credit', models.IntegerField(default=100)),
            ],
        ),
    ]
