# Generated by Django 2.1.1 on 2018-11-11 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='release_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='release_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
