# Generated by Django 2.1.1 on 2018-11-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_check',
            field=models.IntegerField(default=0),
        ),
    ]
