# Generated by Django 2.1.1 on 2018-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20181111_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.CharField(max_length=256),
        ),
    ]
