# Generated by Django 2.1.1 on 2018-11-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_notification_user_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciever_id',
            new_name='receiver_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='relevant_user_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.IntegerField(default=-1),
        ),
    ]
