# Generated by Django 2.1.1 on 2018-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20181113_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='label',
            field=models.CharField(default='其它', max_length=256),
        ),
    ]
