# Generated by Django 2.1.1 on 2018-11-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_activity_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user_credit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='good',
            name='user_credit',
            field=models.IntegerField(default=100),
        ),
    ]
