# Generated by Django 2.1.1 on 2018-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20181205_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_check',
            field=models.IntegerField(default=0),
        ),
    ]
